export const meetingAgendaData = [
  {
    title: "主论坛",
    list: [
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content:
          "从数据到智能，AI构建租赁大脑的实践从数据到智能构建租赁大脑的实践之路从数据到智能，AI构建租赁大脑的实践从数据到智能构建租赁大脑的实践之路",
        speaker: "王新东",
        from: "北京知因智慧科技有限飞机公司创始创人",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
    ],
  },
  {
    title: "融资租赁分论坛",
    list: [
      {
        time: "8:10-8:50",
        mainContent: "重磅发布",
        content:
          "从数据到智能，AI构建租赁大脑的实践从数据到智能构建租赁大脑的实践之路",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
    ],
  },
  {
    title: "供应链金融分论坛",
    list: [
      {
        time: "8:10-8:50",
        mainContent: "开幕致辞",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
    ],
  },
  {
    title: "汽车金融分论坛",
    list: [
      {
        time: "8:10-8:50",
        mainContent: "领导致辞",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
      {
        time: "8:10-8:50",
        mainContent: "签到",
        content: "",
        speaker: "王新东",
        from: "深圳市地方金融监督管理局副局长",
      },
    ],
  },
];

export const importantGuestsData = [
  {
    avatar: require("../assets/guests-1.png"),
    name: "王金银",
    company: "北京知因智慧科技有限飞机公司",
    position: "总经理",
  },
  {
    avatar: require("../assets/guests-2.png"),
    name: "王玉锁",
    company: "新奥集团",
    position: "董事局主席",
  },
  {
    avatar: require("../assets/guests-3.png"),
    name: "柳传志",
    company: "马云公益基金会",
    position: "创办人",
  },
  {
    avatar: require("../assets/guests-4.png"),
    name: "邓锋",
    company: "中关村科技租赁股份有限公司",
    position: "总经理",
  },
  {
    avatar: require("../assets/guests-5.png"),
    name: "王金银",
    company: "北京知因智慧科技有限飞机公司",
    position: "创始创人资租赁有限公司总经理",
  },
  {
    avatar: require("../assets/guests-1.png"),
    name: "王金银",
    company: "北京知因智慧科技有限飞机公司",
    position: "总经理",
  },
  {
    avatar: require("../assets/guests-2.png"),
    name: "王玉锁",
    company: "新奥集团",
    position: "董事局主席",
  },
  {
    avatar: require("../assets/guests-3.png"),
    name: "柳传志",
    company: "马云公益基金会",
    position: "创办人",
  },
  {
    avatar: require("../assets/guests-4.png"),
    name: "邓锋",
    company: "中关村科技租赁股份有限公司",
    position: "总经理",
  },
  {
    avatar: require("../assets/guests-5.png"),
    name: "王金银",
    company: "北京知因智慧科技有限飞机公司",
    position: "创始创人资租赁有限公司总经理",
  },
  {
    avatar: require("../assets/guests-1.png"),
    name: "王金银",
    company: "北京知因智慧科技有限飞机公司",
    position: "总经理",
  },
  {
    avatar: require("../assets/guests-2.png"),
    name: "王玉锁",
    company: "新奥集团",
    position: "董事局主席",
  },
  {
    avatar: require("../assets/guests-3.png"),
    name: "柳传志",
    company: "马云公益基金会",
    position: "创办人",
  },
  {
    avatar: require("../assets/guests-4.png"),
    name: "邓锋",
    company: "中关村科技租赁股份有限公司",
    position: "总经理",
  },
  {
    avatar: require("../assets/guests-5.png"),
    name: "王金银",
    company: "北京知因智慧科技有限飞机公司",
    position: "创始创人资租赁有限公司总经理",
  },
  {
    avatar: require("../assets/guests-1.png"),
    name: "王金银",
    company: "北京知因智慧科技有限飞机公司",
    position: "总经理",
  },
  {
    avatar: require("../assets/guests-2.png"),
    name: "王玉锁",
    company: "新奥集团",
    position: "董事局主席",
  },
  {
    avatar: require("../assets/guests-3.png"),
    name: "柳传志",
    company: "马云公益基金会",
    position: "创办人",
  },
  {
    avatar: require("../assets/guests-4.png"),
    name: "邓锋",
    company: "中关村科技租赁股份有限公司",
    position: "总经理",
  },
  {
    avatar: require("../assets/guests-5.png"),
    name: "王金银",
    company: "北京知因智慧科技有限飞机公司",
    position: "创始创人资租赁有限公司总经理",
  },
];
